#!/usr/bin/env python3

import shutil
import os
import sys
import random


COLUMNS, LINES = shutil.get_terminal_size()

__version__='0.3'

# 23 char
LOGO = 'Made in Canada 🍁'

RNDCLR = random.randint(16, 232)
LID = COLUMNS - 2
BAR = COLUMNS - 23
LOGOLINE = COLUMNS - 26
print('\n\033[m' + '╭' + '─' * LID + '╮' + '\n\n' + '╰' + '─' * LID + '╯\n' + ' ' * LOGOLINE + '\033[m' + LOGO + '\n\n\n')
searchq = input('\033[6A\r' + '│' + '\033[01;38;5;32m Ｇ\033[38;5;160mｏ\033[38;5;215mｏ\033[38;5;32mｇ\033[38;5;34mｌ\033[38;5;160mｅ\033[38;5;15m：\033[m' + '\033[07m' + ' ' * BAR + '\033[m \033[38;5;' + str(RNDCLR) + 'm 🔍  \033[m ' + '│' + '\r' + '│' + '\033[01;38;5;32m Ｇ\033[38;5;160mｏ\033[38;5;215mｏ\033[38;5;32mｇ\033[38;5;34mｌ\033[38;5;160mｅ\033[38;5;15m：\033[m' + '\033[07m ')
print('\033[m\n')
print('\033[m     Showing results for: "\033[01;38;5;51m' + searchq + '\033[m"')
os.system('googler --colors BmcgxX -n 5 ' + searchq)

